controller_manager:
  ros__parameters:
    update_rate: 50

    diff_cont:
      type: diff_drive_controller/DiffDriveController
      ros__parameters:
        left_wheel_names: ["left_wheel_joint"]
        right_wheel_names: ["right_wheel_joint"]
        wheel_separation: 0.36
        wheel_radius: 0.06
        publish_rate: 50.0
        base_frame_id: base_link
        cmd_vel_timeout: 0.5
        use_stamped_vel: false
        odom_frame_id: odom
        enable_odom_tf: true
        open_loop: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

